version: '3.1'

services:


  mysql:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: mysql-db
      MYSQL_ROOT_PASSWORD: 123
      
    ports:
      - "3306:3306"
    volumes:
      - ./data/conf.d:/etc/mysql/conf.d
      - ./data/logs:/logs
      - /usr/local/var/mysql:/var/lib/mysql